spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/books?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # 配置打印 MyBatis日志
    map-underscore-to-camel-case: true #配置驼峰自动转换
  # 配置 mybatis xml 的文件路径，在 resources/mapper 创建所有表的 xml 文件
  mapper-locations: classpath:mapper/**Mapper.xml
# 设置日志文件里的文件名
logging:
  file:
    path: /logger/spring-book.log