#端口号
#server:
#  port: 8080
#数据库相关配置
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test2?characterEncoding=utf8&useSSL=false
#    username: root
#    password: 1234
#
#  banner:
#    location: banner.txt

demo:
  key1: hello,yml
  key2: hello,key2
  key3: ''
# ~表示null
string:
  str1: Hello \n Spring Boot.
  str2: 'Hello \n Spring Boot.'
  str3: "Hello \n Spring Boot."

# yml配置对象
student:
  id: 18
  name: zhangsan
  age: 18

#yml配置集合
dbtypes:
  name:
    - mysql
    - sqlserver
    - db2
  map:
    k1: kk1
    k2: kk2
    k3: kk3

#设置打印日志的级别
#对日志进行分目录打印
logging:
  level:
    root: info
    com:
      example:
        ioc: error
  file:
    name: logger/aaa.log
#    path: logger1
#    日志分割
  logback:
    rollingpolicy:
      max-file-size: 50MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log